name: brainage_estimation
channels:
  - conda-forge
  - defaults
dependencies:
  - Python==3.9.1
  - pip==23.3.1
  - asttokens==2.0.5
  - backcall==0.2.0
  - certifi==2021.10.8
  - charset-normalizer==2.0.12
  - commonmark==0.9.1
  - convertdate==2.4.0
  - cycler==0.11.0
  - decorator==5.1.1
  - executing==0.8.3
  - fonttools==4.31.2
  - numpy==1.22.3
  - idna==3.3
  - ipython==8.2.0
  - jedi==0.18.1
  - joblib==1.1.0
  - kiwisolver==1.4.2
  - lunardate==0.2.0
  - lxml==4.8.0
  - matplotlib==3.5.1
  - matplotlib-inline==0.1.3
  - natsort==8.1.0
  - nibabel==3.2.2
  - nilearn==0.9.1
  - packaging==21.3
  - pandas==1.4.2
  - parso==0.8.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - Pillow==9.1.0
  - prompt-toolkit==3.0.29
  - ptyprocess==0.7.0
  - pure_eval==0.2.2
  - Pygments==2.11.2
  - pyluach==1.4.1
  - pyparsing==3.0.7
  - python-dateutil==2.8.2
  - pytz==2022.1
  - requests==2.27.1
  - rich==12.2.0
  - scikit-learn==1.0.2
  - scipy==1.8.0
  - seaborn==0.11.2
  - six==1.16.0
  - stack_data==0.2.0
  - threadpoolctl==3.1.0
  - traitlets==5.1.1
  - urllib3==1.26.9
  - wcwidth==0.2.5
  - workalendar==16.3.0
  - glmnet==2.2.1
  - pip:
    - julearn==0.2.5
    - PyMeeus==0.5.11
    - xgboost==1.6.0
    - https://github.com/JamesRitchie/scikit-rvm/archive/b5b5f0a062b877f9cbaae219113a7e7b5a19b881.zip
    - .
